spring.application.name=E-commerce

spring.datasource.url=jdbc:mysql://localhost:3306/SpringProjectEcommerce
spring.datasource.username=adminuser
spring.datasource.password=StrongPassword123!

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=paras.kapoor@tothenew.com
spring.mail.password=vkdv xquf jchr obqt

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8