spring.application.name=E-commerce

spring.datasource.url=jdbc:mysql://localhost:3306/SpringProject
spring.datasource.username=adminuser
spring.datasource.password=StrongPassword123!

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true